service: cart-api-service

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1  # Set to 1 to enable connection reuse, or 0 to disable
    NODE_OPTIONS: '--trace-warnings --enable-source-maps --stack-trace-limit=1000'

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  main:
    handler: src/main.handler
    memorySize: 256
    events:
      - http:
          method: ANY
          path: /{proxy+}
          cors: true
